version: '3.8'

services:
  app:
    build: .
    container_name: coding-interview-backend
    ports:
      - '3000:3000' # Mapea el puerto 3000 del contenedor al puerto 3000 del host
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development